# Generated by Django 3.2.4 on 2021-06-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('World', 'World'), ('Technology', 'Technology'), ('Design', 'Design'), ('Culture', 'Culture'), ('Business', 'Business'), ('Politics', 'Politics'), ('Science', 'Science'), ('Health', 'Health'), ('Style', 'Style'), ('Travel', 'Travel')], default='World', max_length=100)),
                ('short', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('date_post', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('make_headblog', models.BooleanField(default=False)),
            ],
        ),
    ]
