# Generated by Django 3.2.4 on 2021-06-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='make_headblog',
            new_name='headblog',
        ),
    ]
